BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `users` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`ryzom_id`	INTEGER NOT NULL UNIQUE,
	`name`	TEXT NOT NULL,
	`settings`	TEXT NOT NULL DEFAULT '{}'
);
CREATE TABLE IF NOT EXISTS `bosses` (
	`id`	INTEGER NOT NULL,
	`name`	TEXT NOT NULL,
	`region`	TEXT NOT NULL,
	`level`	INTEGER NOT NULL,
	`time`	INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);
COMMIT;
